global using Microsoft.AspNetCore.Authentication.Cookies;
global using System.Diagnostics;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Authorization;
global using System.ComponentModel.DataAnnotations;
global using System.Security.Claims;
global using Microsoft.AspNetCore.Authentication;
global using StoreManagement.WebApp;
global using Microsoft.AspNetCore.Mvc.Rendering;